Add shopping cart and cart item models
chertiav/online-book-store-app pull request #11
Opened 2024-12-29 17:36 UTC by chertiav

- introduced shopping cart and cart item models,
- created repositories, services, mappers, controllers, and database schema changes.
- added endpoints for shopping cart and cart item management, such as adding and updating cart items.
- integrated shopping cart creation during user registration and implemented soft delete for both models.

2024-12-30 10:34 UTC, liliia-ponomarenko requested changes
Good job! Let’s improve your solution ;)

2024-12-30 10:34 UTC, liliia-ponomarenko commented on pom.xml
> +        </dependency>
do you really need this dependency?

2024-12-30 10:34 UTC, liliia-ponomarenko commented on src/main/java/com/achdev/onlinebookstoreapp/controller/CartItemController.java
> +@PreAuthorize("hasRole('ROLE_USER')")
Don’t  use a general security setup

2024-12-30 10:34 UTC, liliia-ponomarenko commented on src/main/java/com/achdev/onlinebookstoreapp/controller/ShoppingCartController.java
> +            @AuthenticationPrincipal UserDetails userDetails
Let’s  use Authentification

2024-12-30 10:34 UTC, liliia-ponomarenko commented on src/main/java/com/achdev/onlinebookstoreapp/controller/ShoppingCartController.java
> +    public void addCartItem(
Better return some object in response (check task description)

2024-12-30 10:34 UTC, liliia-ponomarenko commented on src/main/java/com/achdev/onlinebookstoreapp/dto/cart/item/CartItemBaseRequestDto.java
> +public abstract class CartItemBaseRequestDto {
Why is it an abstract class?

2024-12-30 10:34 UTC, liliia-ponomarenko commented on src/main/java/com/achdev/onlinebookstoreapp/dto/cart/item/CartItemBaseRequestDto.java
> +    @NotNull(message = "Quantity cannot be null")
primitive type can't be null

2024-12-30 10:34 UTC, liliia-ponomarenko commented on src/main/java/com/achdev/onlinebookstoreapp/dto/cart/item/CartItemBaseRequestDto.java
> +    @Digits(integer = 6, fraction = 0, message = "Quantity should be a valid integer number")
do you really need this annotation?

2024-12-30 10:34 UTC, liliia-ponomarenko commented on src/main/java/com/achdev/onlinebookstoreapp/dto/cart/item/CartItemBaseRequestDto.java
> +    @Min(value = 0, message = "Quantity must be 0 or greater than zero")
Let’s use Positive

2024-12-30 10:34 UTC, liliia-ponomarenko commented on src/main/java/com/achdev/onlinebookstoreapp/dto/cart/item/CartItemRequestDto.java
> +@JsonIgnoreProperties(ignoreUnknown = true)
```suggestion
```

2024-12-30 10:34 UTC, liliia-ponomarenko commented on src/main/java/com/achdev/onlinebookstoreapp/dto/cart/item/CartItemRequestDto.java
> +public class CartItemRequestDto extends CartItemBaseRequestDto {
I don’t recommend complicated dto using inheritance. DTO is a simple object

2024-12-30 10:34 UTC, liliia-ponomarenko commented on src/main/java/com/achdev/onlinebookstoreapp/mapper/BookMapper.java
> +                .orElse(null);
Don’t  return null from methods

2024-12-30 10:34 UTC, liliia-ponomarenko commented on src/main/java/com/achdev/onlinebookstoreapp/repository/shopping/cart/ShoppingCartRepository.java
> +    Optional<ShoppingCart> findByUser_Email(String userEmail);
```suggestion
    Optional<ShoppingCart> findByUserEmail(String userEmail);
```

2024-12-30 10:34 UTC, liliia-ponomarenko commented on src/main/java/com/achdev/onlinebookstoreapp/service/impl/ShoppingCartServiceImpl.java
> +        if (bookService.findById(requestDto.getBookId()) == null) {
is it possible?

2024-12-30 10:34 UTC, liliia-ponomarenko commented on src/main/java/com/achdev/onlinebookstoreapp/service/impl/ShoppingCartServiceImpl.java
> +        if (getCartItemByBookId(shoppingCart, cartItem) == null) {
the same

2024-12-30 10:34 UTC, liliia-ponomarenko commented on src/main/java/com/achdev/onlinebookstoreapp/service/impl/ShoppingCartServiceImpl.java
> +                .orElse(null);
Don’t return null from the method

2024-12-30 10:34 UTC, liliia-ponomarenko commented on src/main/java/com/achdev/onlinebookstoreapp/service/impl/ShoppingCartServiceImpl.java
> +                        .equals(cartItem.getBook().getId()))
can you make it on the query level?

2024-12-30 10:34 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/10-create-cart_item-table.yaml
> +            referencedTableName: shopping_carts
add one empty line (check other files)

2025-01-02 09:39 UTC, chertiav commented on pom.xml
> +        </dependency>
++

2025-01-02 09:40 UTC, chertiav commented on src/main/java/com/achdev/onlinebookstoreapp/controller/CartItemController.java
> +@PreAuthorize("hasRole('ROLE_USER')")
++

2025-01-02 09:54 UTC, chertiav commented on src/main/java/com/achdev/onlinebookstoreapp/controller/ShoppingCartController.java
> +            @AuthenticationPrincipal UserDetails userDetails
++

2025-01-02 10:17 UTC, chertiav commented on src/main/java/com/achdev/onlinebookstoreapp/repository/shopping/cart/ShoppingCartRepository.java
> +    Optional<ShoppingCart> findByUser_Email(String userEmail);
++

2025-01-02 10:29 UTC, chertiav commented on src/main/java/com/achdev/onlinebookstoreapp/mapper/BookMapper.java
> +                .orElse(null);
++

2025-01-02 12:18 UTC, chertiav commented on src/main/java/com/achdev/onlinebookstoreapp/dto/cart/item/CartItemRequestDto.java
> +@JsonIgnoreProperties(ignoreUnknown = true)
++

2025-01-02 14:22 UTC, chertiav commented on src/main/java/com/achdev/onlinebookstoreapp/controller/ShoppingCartController.java
> +    public void addCartItem(
++

2025-01-02 14:22 UTC, chertiav commented on src/main/java/com/achdev/onlinebookstoreapp/dto/cart/item/CartItemBaseRequestDto.java
> +public abstract class CartItemBaseRequestDto {
++

2025-01-02 14:25 UTC, chertiav commented on src/main/java/com/achdev/onlinebookstoreapp/dto/cart/item/CartItemBaseRequestDto.java
> +    @Digits(integer = 6, fraction = 0, message = "Quantity should be a valid integer number")
++

2025-01-02 14:27 UTC, chertiav commented on src/main/java/com/achdev/onlinebookstoreapp/dto/cart/item/CartItemRequestDto.java
> +public class CartItemRequestDto extends CartItemBaseRequestDto {
++

2025-01-02 14:28 UTC, chertiav commented on src/main/java/com/achdev/onlinebookstoreapp/dto/cart/item/CartItemBaseRequestDto.java
> +    @Min(value = 0, message = "Quantity must be 0 or greater than zero")
++

2025-01-02 14:29 UTC, chertiav commented on src/main/java/com/achdev/onlinebookstoreapp/dto/cart/item/CartItemBaseRequestDto.java
> +    @NotNull(message = "Quantity cannot be null")
++

2025-01-02 14:30 UTC, chertiav commented on src/main/java/com/achdev/onlinebookstoreapp/service/impl/ShoppingCartServiceImpl.java
> +        if (bookService.findById(requestDto.getBookId()) == null) {
++

2025-01-02 14:30 UTC, chertiav commented on src/main/java/com/achdev/onlinebookstoreapp/service/impl/ShoppingCartServiceImpl.java
> +        if (getCartItemByBookId(shoppingCart, cartItem) == null) {
++

2025-01-02 14:30 UTC, chertiav commented on src/main/java/com/achdev/onlinebookstoreapp/service/impl/ShoppingCartServiceImpl.java
> +                .orElse(null);
++

2025-01-02 14:30 UTC, chertiav commented on src/main/java/com/achdev/onlinebookstoreapp/service/impl/ShoppingCartServiceImpl.java
> +                        .equals(cartItem.getBook().getId()))
++

2025-01-02 14:31 UTC, chertiav commented on src/main/resources/db/changelog/changes/10-create-cart_item-table.yaml
> +            referencedTableName: shopping_carts
++

2025-01-03 07:50 UTC, liliia-ponomarenko approved these changes
Good job! But fix my comment before merging

2025-01-03 07:50 UTC, liliia-ponomarenko commented on src/main/java/com/achdev/onlinebookstoreapp/repository/shopping/cart/ShoppingCartRepository.java
> +    //    ShoppingCart save(ShoppingCart shoppingCart);
Let’s  remove the commented code

2025-01-03 08:11 UTC, chertiav commented on src/main/java/com/achdev/onlinebookstoreapp/repository/shopping/cart/ShoppingCartRepository.java
> +    //    ShoppingCart save(ShoppingCart shoppingCart);
++

2025-01-03 11:08 UTC, merged